inputs:
  server:
    description: "FTPサーバー名"
    required: true
  user:
    description: "FTPユーザー名"
    required: true
  password:
    description: "FTPパスワード"
    required: true
  remote:
    description: "リモート側のパス"
    required: true
  local:
    description: "ローカル側のパス"
    required: true
  mirror:
    description: "ミラーリングするかどうか"
    required: false
    default: false
runs:
  using: "composite"
  steps:
    - name: .NETセットアップ済みか確認
      id: dotnet_setup_completed
      shell: pwsh
      run: |
        $result = Start-Process dotnet -ArgumentList "--version" -Wait -PassThru
        if ($result.ExitCode -eq 0) {
          Write-Output "dotnet setup completed"
          Write-Output "result=ok" >> $GITHUB_OUTPUT
        }else{
          Write-Output "dotnet setup not completed"
          Write-Output "result=ng" >> $GITHUB_OUTPUT
        }
    - if: steps.dotnet_setup_completed.outcome == 'failure'
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    - name: .NETバージョン確認
      shell: pwsh
      run: |
        dotnet --version
    - name: カレントディレクトリを確認
      shell: pwsh
      run: |
        pwd
    - name: .NETプロジェクトを実行
      shell: pwsh
      run: |
        $ProjFilePath = Join-Path "${{ github.action_path }}" "ftp-upload.csproj"
        dotnet run --project $ProjFilePath `
                   --server ${{ inputs.server }} `
                   --user ${{ inputs.user }} `
                   --password ${{ inputs.password }} `
                   --remote ${{ inputs.remote }} `
                   --local ${{ inputs.local }} `
                   --mirror ${{ inputs.mirror}}
