runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: .NETバージョン確認
      shell: pwsh
      run: |
        dotnet --version
    - name: カレントディレクトリを確認
      shell: pwsh
      run: |
        pwd
    - name: .NETプロジェクトを実行
      shell: pwsh
      run: |
        dotnet run --project ftp-upload.csproj
