inputs:
  server:
    description: "FTPサーバー名"
    required: true
  user:
    description: "FTPユーザー名"
    required: true
  password:
    description: "FTPパスワード"
    required: true
  remote:
    description: "リモート側のパス"
    required: true
  local:
    description: "ローカル側のパス"
    required: true
  mirror:
    description: "ミラーリングするかどうか"
    required: false
    default: false
runs:
  using: "composite"
  steps:
    - uses: actions/setup-dotnet@v3
    - name: .NETバージョン確認
      shell: pwsh
      run: |
        dotnet --version
    - name: カレントディレクトリを確認
      shell: pwsh
      run: |
        pwd
    - name: .NETプロジェクトを実行
      shell: pwsh
      run: |
        $ProjFilePath = Join-Path "${{ github.action_path }}" "ftp-upload.csproj"
        dotnet run --project $ProjFilePath `
                   --server ${{ inputs.server }} `
                   --user ${{ inputs.user }} `
                   --password ${{ inputs.password }} `
                   --remote ${{ inputs.remote }} `
                   --local ${{ inputs.local }} `
                   --mirror ${{ inputs.mirror}}
