name: release
on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: V1タグを更新
        run: |
          git push -d origin v1
          git tag v1
          git push origin v1
